name: Add Jira Timeline Comment on Project Column Move

on:
  project_card:
    types: [moved]

jobs:
  update-jira-timeline:
    runs-on: ubuntu-latest

    steps:
      - name: Get project card info
        uses: actions/github-script@v7
        id: get_card_info
        with:
          script: |
            const card = await github.rest.projects.getCard({
              card_id: context.payload.project_card.id
            });

            const column = await github.rest.projects.getColumn({
              column_id: context.payload.project_card.column_id
            });

            return {
              content_url: card.data.content_url,
              column_name: column.data.name
            };

      - name: Get issue details
        if: steps.get_card_info.outputs.content_url != null
        uses: actions/github-script@v7
        id: get_issue
        with:
          script: |
            const contentUrl = JSON.parse(process.env.CONTENT_URL);
            const issue = await github.request(contentUrl);
            return {
              title: issue.data.title,
              body: issue.data.body
            };
        env:
          CONTENT_URL: ${{ steps.get_card_info.outputs.content_url }}

      - name: Extract Jira issue key
        id: extract_key
        run: |
          echo "Extracting Jira key from issue description..."
          BODY="${{ fromJson(steps.get_issue.outputs.result).body }}"
          if [[ "$BODY" =~ ([A-Z]+-[0-9]+) ]]; then
            echo "key=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No Jira key found in description."
            exit 1
          fi


      - name: Add comment to Jira issue
        run: |
          COLUMN="${{ fromJson(steps.get_card_info.outputs.result).column_name }}"
          COMMENT="🕒 GitHub issue moved to column: *${COLUMN}* by \`${{ github.actor }}\` on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          curl -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "{\"body\": \"$COMMENT\"}" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract_key.outputs.key }}/comment"
